export {default as Prompt} from './Prompt'
export {default as Instuctions} from './Instructions'
export {default as Choice} from './Choice'
export {default as Ending} from './Ending'
export {default as GameContainer} from '../containers/GameContainer'
export {default as WelcomeContainer} from '../containers/WelcomeContainer'